# Default initial positions for motoman_sia5f's ros2_control fake system

initial_positions:
  joint_b: -1.0076
  joint_e: 0
  joint_l: -0.944
  joint_r: 0
  joint_s: 0
  joint_t: 0
  joint_u: -0.8393
  right_joint: 0
